### ISSUE TITLE
CSS attribute selectors in media queries

### ISSUE THREAD

**Issue by redbar0n** [Sharcoux/rn-css#12]
In styled-components, you can use [CSS attribute selectors](https://www.w3schools.com/css/css_attribute_selectors.asp) in media queries, like in regular CSS:

```css
@media screen and (min-width: 1024px){
  #componentId[data-responsive=“true”] {
    padding-top: 100px;
    background-color: red;
  }
}
```

Is this possible in rs-css?
